#!/bin/bash
# wrap the pt-stalk to get system report when cpu is higher than 600%

set -e 
[ "$DEBUG" ] && set -x

. /root/.bash_profile
export IF=$1
PORT=$2

if [ $# -ne 2 ]; then
    echo "Usage: $0 interface mysql-port"
    exit 1
fi

IP=$(ip addr | perl -ne '$a = 1 if m/$ENV{IF}:/; \
     do { print $1; exit 0 } if (m#inet (\d+\.\d+\.\d+\.\d+)/24 brd#ig and $a)')

# current dir
CURDIR=$(dirname $0)
# send mysql client config to pt-stalk

(
   flock -x -n 300
   if [[ $? -ne 0 ]]; then
     echo "Failed acquiring lock"
     exit 1
   fi

  printf \
  "%s\n" \
  "[client]" \
  "user=$(echo -n eHh4eHh4 | base64 -d)" \
  "password=$(echo -n eHh4eHh4 | base64 -d)" \
  "host=$IP" \
  "port=$PORT" >$CURDIR/db_$PORT\.cnf

  $CURDIR/pt-stalk --defaults-file=$CURDIR/db_$PORT\.cnf --sleep 40 --function \
    "$CURDIR/plugin/trg_cpu_usage" --threshold 500 --collect-tcpdump --cycles=3 \
    --log $CURDIR/log/pt-stalk.log --notify-by-email sysadmin@admin.com \
    --pid=$CURDIR/pid/pid_$PORT --daemonize
) 300> $CURDIR/lock/run_$PORT.lock
